### ISSUE TITLE
chat: emoji picker

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1395]
A chaser for #1393 (a "fix" proposed in #1394) : I wonder how much work would adding emoji picker such as e.g. https://github.com/missive/emoji-mart would be?

**Comment by 0xdevalias** [comment]
@yarikoptic Interesting you should raise this, as it's something I had looked into a bit and included on part of our backlog. I hadn't gone deep on making all of the decisions/explorations around this yet, but I'll include relevant snippets below (note: you won't be able to see any of the 'internal' issues that are linked)

> Some resources I stumbled across the other day, capturing here for posterity:
> 
> - https://github.com/missive/emoji-mart
>   - > Emoji Mart is a Slack-like customizable emoji picker component for React
>   - https://github.com/missive/emoji-mart#custom-emojis
>     - > You can provide custom emojis which will show up in their own category. You can either use a single image as imageUrl or use a spritesheet as shown in the second object.
>   - https://github.com/missive/emoji-mart#custom-icons
>     - > You can provide custom icons which will override the default icons.
>   - https://github.com/missive/emoji-mart#storage
>     - > By default EmojiMart will store user chosen skin and frequently used emojis in localStorage. That can however be overwritten should you want to store these in your own storage.
>   - https://github.com/missive/emoji-mart#multiple-sets-supported
>     - > Apple / Google / Twitter / Facebook
> - https://github.com/joypixels/emojione
>   - > [Archived] The world's largest independent emoji font. Maintained at joypixels/emoji-toolkit.
> - https://github.com/joypixels/emoji-toolkit
>   - > The world's largest independent emoji font.
>   - > A set of libraries to help users find and replace native system emojis with JoyPixels (formerly EmojiOne) in their app or website.
>   - Note: you need a commercial licence to use this
>     - https://www.joypixels.com/licenses/premium
>   - https://www.joypixels.com/emoji
> - https://github.com/EmojiTwo/emojitwo
>   - > Fork of the last fully free EmojiOne™ 2 artwork
>   - > The artwork of the second generation of the web's first complete open source emoji set. It is and will stay 100% free and open source.
> - https://github.com/iamcal/emoji-data
>   - > Easy to parse data and spritesheets for emoji
>   - > This project provides easy-to-parse data about emoji, along with a spritesheet-style images for use on the web.
>   - > The current version supports Emoji version 13 (2020)
>   - https://github.com/iamcal/emoji-data#installation
>     - > The git repo is pretty big (almost 4GB), but contains everything.
>     - > If you want to use npm, you can: `npm install emoji-datasource`. This will only install the 32px full-fidelity spritesheets (with fallback images). If you want different size sheets (16, 20 or 64px), quantized sheets (128 or 256 color), non-fallback (clean) sheets, or the individual images (at 64px) then you'll need to install additional npm modules.
> 
> _Originally posted by @0xdevalias in https://github.com/sparkletown/internal-sparkle-issues/issues/188#issuecomment-817416820_

**Comment by 0xdevalias** [comment]
> [OOS] While it's OOS for this PR, in future we could likely use this same lib/pattern to enhance our existing 'reactions' feature as well. Currently it just uses hardcoded emoji:
> 
> - https://github.com/sparkletown/sparkle/blob/staging/src/types/reactions.ts#L46-L103
> 
> Some of the related files:
> 
> - https://github.com/sparkletown/sparkle/search?q=reactions
>   - https://github.com/sparkletown/sparkle/blob/staging/src/types/reactions.ts
>   - https://github.com/sparkletown/sparkle/blob/staging/src/utils/reactions.ts
>   - https://github.com/sparkletown/sparkle/blob/staging/src/hooks/reactions.tsx
>   - https://github.com/sparkletown/sparkle/blob/staging/src/components/molecules/UserReactions/UserReactions.tsx
>   - https://github.com/sparkletown/sparkle/blob/staging/src/components/templates/ReactionPage/ReactionList.tsx#L26
>   - etc
> 
> We also have a backlog issue (scheduled to be worked on soon, after a couple of higher priority features) to clean up all of the 'send reaction' buttons/etc across the codebase into a single canonical component + logic in a hook, etc (currently each venue template has it's own duplicated code for rendering the 'reaction buttons' in places like the Jazz Bar, Auditorium (`Audience`), etc:
> 
> - 🔒 https://github.com/sparkletown/internal-sparkle-issues/issues/637
> 
> _Originally posted by @0xdevalias in https://github.com/sparkletown/sparkle/issues/1394#issuecomment-841598849_

**Comment by 0xdevalias** [comment]
> @0xdevalias @soichih added emoji-mart picker here to see how it all would look. Wdyt?
> 
> _Originally posted by @yarikoptic in https://github.com/sparkletown/sparkle/issues/1383#issuecomment-845900638_
