### ISSUE TITLE
Venue Map flickers when it opens 

### ISSUE THREAD

**Issue by soichih** [sparkletown/sparkle#1402]
On chrome, when I first open a Venue, all the rooms are collapsed at the top for a second or so before showing the map correctly.

![image](https://user-images.githubusercontent.com/923896/118371889-9c6ea080-b57c-11eb-8820-3411c6e60ffb.png)

**Comment by yarikoptic** [comment]
confirming that I was observing the same

**Comment by 0xdevalias** [comment]
This is definitely a common occurrence. I haven’t looked deeply into the specifics of the ‘why’ of this before, but my guess/gut feel is that it may relate to the height that is being set on the PartyMap/Map by default, which is then only changed once it is loaded. If you wanted to dig into it, that would be where I would start looking.

**Comment by yarikoptic** [comment]
I did observe this issue often in the past but have not spotted it recently . I wonder if it is still relevant or was somehow resolved without #1403 which then could be closed along with this one?

**Comment by mobilevinay** [comment]
migrated to zenhub, check!
