### ISSUE TITLE
Could not proxy request /in/undefined from localhost:3000 to http://localhost:3001.

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1405]
While working with a local instance, I get those .  So decided to ask:
- is that expected
- shouldn't there be some `/undefined` end point and/or why we have it (env/ohbm branch)

```
Compiled successfully!

You can now view co-reality-map in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.34:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

Proxy error: Could not proxy request /in/undefined from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /in/undefined from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

```

**Comment by 0xdevalias** [comment]
There isn’t an ‘undefined’ endpoint, in my experience this is a result of an undefined variable being used as part of a string, quite likely used to try and load an image. The place I’ve seen it most often is in styles that try and do something like ‘url(/in/${foo?.bar})’ or similar.

**Comment by yarikoptic** [comment]
you are correct -- it is an image. FWIW: haven't identified the source. I thought it might be related somehow to that flicker issue @soichih  is trying to fix, but it is still there with 018709f010c5cb1d8542251bbbf13ab0d30692c3 of #1403 .  In the 

<details>
<summary>nearby hits not suggestive</summary> 

```
users%2FA27sVVc9dZOLVWztkHw9EJj807g1%2Fvenues%2Fho…=media&amp;token=63630e14-b599-4d23-a82c-7cdfb6fa7ee2 | GET | 200 | jpeg | react-dom.development.js:1350 | 868&nbsp;kB | 1.04&nbsp;s
-- | -- | -- | -- | -- | -- | --
data:image/png;base… | GET | 200 | png | home | (memory cache) | 0&nbsp;ms
data:image/png;base… | GET | 200 | png | home | (memory cache) | 0&nbsp;ms
data:image/png;base… | GET | 200 | png | home | (memory cache) | 0&nbsp;ms
undefined | GET | 500 | text/plain | home | 111&nbsp;B | 491&nbsp;ms
users%2FA27sVVc9dZOLVWztkHw9EJj807g1%2Fvenues%2Fho…=media&amp;token=7476824b-7da8-46cc-b6ab-3525ca712e0d | GET | 200 | png | home

```
</details>

**Comment by yarikoptic** [comment]
since I don't see it for the live https://ohbm.sparkle.space/in/home instance - I guess it might relate to all those "failing to init" services such as stripe (https://github.com/sparkletown/sparkle/issues/1388) which is yet to be disabled.

**Comment by 0xdevalias** [comment]
> since I don't see it for the live https://ohbm.sparkle.space/in/home instance - I guess it might relate to all those "failing to init" services such as stripe (#1388) which is yet to be disabled.

@yarikoptic I would be very surprised if it was related to any of those. The url path implies it’s within the sparkle codebase. You’re not going to see the exact error on any live instance because that error is coming from the local emulator. But you’ll almost certainly still see a 404 trying to access that url lath if you look at your network requests.

**Comment by yarikoptic** [comment]
I do not observe it ATM with 0407792e87b497becdaf091ff9dfc7fc7c2273d7 state so I guess it is resolved. stripe error (#1388) is still there so indeed is unrelated then.
