### ISSUE TITLE
minor: getLinkFromText might need to avoid per-word Fragment

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1412]
Discovered while considering it in some shape or form for also rendering emojis and urls in the chat messages.
ATM it creates a separate ` return <React.Fragment key={index}>{word} </React.Fragment>;` for each non-url word thus making it 

![image](https://user-images.githubusercontent.com/39889/118518759-737a1700-b706-11eb-953d-e78941b59079.png)

IMHO for no benefit since it could have stayed at least a single string.  I do not know if that would provide any notable benefit performance wise but I would assume so?  Could be easily addressed within  `getLinkFromText` but accumulating words until needed to be output (e.g. when hitting some non-text fragment like a url or an emoji; or reaching the end and still have some accumulated)

Feel welcome to close  if no notable benefit to be gained

**Comment by 0xdevalias** [comment]
@yarikoptic Thanks for raising this and pointing it out.

I don’t believe this would cause any perceivable performance issues, and if anywhere related to it would, I expect would come from the actual initial processing of the text itself (which would need to be done to accumulate the results anyway).

I’ll close this for now, but if you do come across anything else that suggests it is having a performance impact, feel feee to comment here with more info and we can reopen it and explore deeper.
