### ISSUE TITLE
cannot take a seat in "0-th" row in the auditorium

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1422]
![cannot-take-seat-middlerow](https://user-images.githubusercontent.com/39889/118840345-4f990b80-b895-11eb-9e79-391a231e072e.gif)

you can see that no seat assigned when I click in that "middle row"

**Comment by 0xdevalias** [comment]
@yarikoptic Have you looked any further into the 'why' of this? In particular it would be extremely helpful to know the minimal steps to reproduce this (ideally locally/within a fresh auditorium if possible), and potentially also the existing venue URL you noticed this in + exactly which row/column it is that is impacted by this.

**Comment by yarikoptic** [comment]
Iirc it was in the main auditorium for the ohbm . Ii will try tomorrow again. Can you try also - can you take a seat in any row to the right from the screen?

**Comment by yarikoptic** [comment]
FWIW there were no new errors in browser console

**Comment by yarikoptic** [comment]
minimal steps for me is to go to main page https://ohbm.sparkle.space/in/home, go to main auditorium, enter to https://ohbm.sparkle.space/in/mainauditorium and try to take a seat in that middle row (didn't do counting).

<details>
<summary>here is a larger gif showing that it reproduces for the "second" of me</summary> 

![cannot-take-seat-middlerow-large](https://user-images.githubusercontent.com/39889/119038328-00300980-b981-11eb-89dd-6c56a4ddc15c.gif)

</details>

this time it was as another user on the main instance. Original report I think was on a local development instance (different user).  The question is either I am special or it is present for anyone else?  I have no clue "why" it might be happening

**Comment by htwangtw** [comment]
I can reproduce the error exactly the way @yarikoptic described above and in my local instance. 
I did the counting - the bug is present for any seat of the 10th-row counting from the top.

**Comment by yarikoptic** [comment]
FWIW, internally it is "0th" row.  It seems to get to `makeUpdateUserGridLocation` so I guess it does update location in DB but just doesn't render avatar properly for 0th row.

**Comment by soichih** [comment]
My guess is that, 0th row was supposed to be used as a virtual collider - just like there is a virtual collider on the 0th column.

![image](https://user-images.githubusercontent.com/923896/119215323-f995b500-ba9a-11eb-826d-3d82eb46afc8.png)

I kind of like that there is a virtual collider at 0th row - in case there was a virtual fire or, some kind of virtual emergency that people has to evacuate virtually.

**Comment by 0xdevalias** [comment]
> My guess is that, 0th row was supposed to be used as a virtual corridor - just like there is a virtual corridor on the 0th column.

That was my thoughts too. If there is, it’s likely that it may have been removed from the ‘is this a seat’ code, but maybe not from the ‘can I sit here’ code.

Have a look in the Audience component, that’ll be where to find this stuff (though it’s a pretty hack/complex piece of legacy code at the moment)

My other potential theory is that the code is registering that someone is already ‘sitting there’, but that they may not be a ‘recent user’ (which is why they aren’t being rendered there. Which if that’s the case, sounds like a bug.

**Comment by yarikoptic** [comment]
suggested fix in https://github.com/sparkletown/sparkle/pull/1439

**Comment by 0xdevalias** [comment]
> suggested fix in #1439

@yarikoptic @htwangtw @soichih Thanks for the debugging, identification, and fix for this! Awesome work.
