### ISSUE TITLE
Add a quick and consistent way to get back to the main page

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1461]
There is a "Back to {venue up}" button which is sufficient to be able to quickly get back to main landing page from 1st level sub-venues.  But a sequence of jumps is needed to percolate from lower levels.  Given that every page load takes seconds of "blue screen of sparkle" it becomes quite unpleasant UX quickly.

Possible solutions I see in order of preference
- full path of breadcrumbs: e.g. like "Back to: [Home]({home}) : [Poster Hall]({posterhall}) : [Poster 111]({poster111})" (if hypothetically we were in some venue within specific poster) -- if there is a clear nesting structure known
- Dedicated Home + Up: e.g. like "Back to: [Home]({home}), [Poster 111]({poster111})" in the above scenario, with the 2nd one being added ONLY if not it is a `{home}` (i.e. that we are just 1 level down)

**Comment by 0xdevalias** [comment]
Reopening to track the other parts mentioned here.

**Comment by mobilevinay** [comment]
migrated to zenhub, check!
