### ISSUE TITLE
venue modal should not list all participants!

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1579]
With @soichih we are testing env/ohbm and main auditorium has >1000 participants ATM. Clicking on "Main auditorium" opens a modal with all 1000 listed BEFORE the schedule block etc, so you need to scroll down for a while to get to what is actually useful...

I think listing first (random) 20 participants and saying "+ 1000 more" would be sufficient.

edit 1:
<details>
<summary>Here is how it looks like -- pay attention to the scroll bar on the right</summary> 

![image](https://user-images.githubusercontent.com/39889/122474101-be4eaf00-cf90-11eb-9357-7cf19752a797.png)

</details>

also all those constantly flicker replacing with others etc, resizing window left me at some point with a stuck view of only the half of the screen, then browser locked up (I have many other tabs though), took minutes to go normal.

limiting number of avatars would help with that I hope.

**Comment by 0xdevalias** [comment]
What component is currently being used there to render them? Off the top of my head the component it should be using already has the functionality to limit how many are being isolated there unless you click to expand them.

**Comment by yarikoptic** [comment]
code is there but by default it seems that all users are shown. Sent https://github.com/sparkletown/sparkle/pull/1598

**Comment by yarikoptic** [comment]
was addressed in #1598 against env/ohbm so didn't close automagically here.
