### ISSUE TITLE
FYI: LogRocket: Session quota exceeded. Please upgrade your plan. Disabling ...

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1581]
while testing https://ohbm.sparkle.space/in/mainauditorium

Here is how it looks like (note other messages, although I must say as soon as we started to test sparkle my wifi network went nuts and unreliable, restared a few times now, and it seems that bandwidth is indeed subpar - yet to figure out)

![image](https://user-images.githubusercontent.com/39889/122475430-a546fd80-cf92-11eb-9dd5-ee33ea519abf.png)

edit: the question is -- shouldn't this logging be disabled for the live event/deployment?

**Comment by 0xdevalias** [comment]
LogRocket is specifically used in production environments for many purposes including the ability to see the ‘breadcrumbs’ leading up to an error to help debug the ‘why’ of it.

It’s a known thing that our session limit gets reached relatively often, we’ve only got a rather low level plan. It’s not a concern for us based on how we are making use of the tool at the moment.

**Comment by 0xdevalias** [comment]
Closing this as ‘not an issue’ based on the above description/reasoning.
