### ISSUE TITLE
search results appear in reversed order in posterhall

### ISSUE THREAD

**Issue by margulies** [sparkletown/sparkle#1604]
The search results for terms (not for authors) are listed in (what appears to be) reverse order. Specifically, posters with the term in the title are listed towards the end.

**Comment by margulies** [comment]
in `hooks/posters.ts` line 200, setting the `title` weight to 20 seems to improve the ordering: 
```
 "name",
          {
            name: "poster.title",
            weight: 24,
          },
```

**Comment by sparkleed** [comment]
This to be merged please, to address reverse search ordering.

**Comment by 0xdevalias** [comment]
@sparkleed this is an issue describing a problem,  not a PR containing a code fix, so can’t be ‘merged’. I will put it on my constantly growing list.

**Comment by margulies** [comment]
Now addressed in https://github.com/sparkletown/sparkle/pull/1606

**Comment by 0xdevalias** [comment]
> @sparkletown/engineering @jonboutelle @sparkletown/product I've merged this into `env/ohbm` as that seems to be where the existing tweaks to search weight/etc have been merged, but I expect these changes would be worth pulling out into our main code branch at some point.
> 
> _Originally posted by @0xdevalias in https://github.com/sparkletown/sparkle/issues/1606#issuecomment-864644972_
