### ISSUE TITLE
Clicking on delete brings up a modal for the author

### ISSUE THREAD

**Issue by yarikoptic** [sparkletown/sparkle#1618]
didn't check staging but on ongoing OHBM 2021 -- it seems to be impossible to delete a message in the chat.  Clocking on trashcan just brings up a modal with my name/profile.

**Comment by whoaitsaimz** [comment]
In my experience, it does in fact delete the message, but the profile modal of the author of deleted message is indeed displayed first, somewhat distracting from the fact that message has been deleted

**Comment by 0xdevalias** [comment]
> somewhat distracting from the fact that message has been deleted

It's all about misdirection _waves hands like a magician_

**Comment by whoaitsaimz** [comment]
I stand corrected, now the messages delete for just a moment and then re-appear
