### ISSUE TITLE
Feature request: Chat/DM activity indicators

### ISSUE THREAD

**Issue by effigies** [sparkletown/sparkle#1633]
Indicators of activity in local chat and DMs would be useful, as it's very easy to forget about them. Many tools use a blue circle to indicate activity, and red to indicate something specifically targeting the user, if it makes sense to adopt an existing convention.

It's unclear if I can @ somebody at a specific location, but if that is possible, it'd be nice to get notifications if someone tries to chat me in a room that I'm not currently in. Or to watch a room (e.g., my poster). I can open additional issues, if you like.

**Comment by effigies** [comment]
Ah, may be a duplicate of #1431.

**Comment by yarikoptic** [comment]
It is very related to #1431 for the initial motivation indeed.  `@somebody` pings and notifications for having replies (and ideally being able to auto-scroll to those threaded messages) would be nice extra features indeed, but those I guess would require additional "tab" to the chat (e.g. "Notifications") .

**Comment by 0xdevalias** [comment]
@ mentions is something I would like to add eventually, even if it doesn’t notify at first and just makes referring to people in chat easier. There’s a lib I’ve used on a past project that I would probably use for this; need to find the name again but.

As for wider notifications/etc, I believe we have some feature stuff designed for that, but not the highest priority at the moment, and I believe there’s going to be a bunch of nuances ‘harder than we might initially think’ aspects to it.

As far as red dot/etc, there is actually a long outdated PR that git abandoned by a firmer engineer that we haven’t had a chance to get back to for adding notification sound + display icon. It could be worth finding that one and seeing what it would take to get it polished up and ready (or at the very least linking here).

**Comment by 0xdevalias** [comment]
> There’s an existing WIP PR for adding sounds and some other things like that for direct messages

This is the PR I was thinking of https://github.com/sparkletown/sparkle/pull/1262 (based on 🔒 https://github.com/sparkletown/internal-sparkle-issues/issues/179)

_Originally posted by @0xdevalias in https://github.com/sparkletown/sparkle/issues/1431#issuecomment-848585957_

**Comment by whoaitsaimz** [comment]
We have added a purple dot to show when you receive DMs
