### ISSUE TITLE
Ability to choose player avatars

### ISSUE THREAD

**Issue by 0xdevalias** [sparkletown/sparkle#590]
I can see that a change was made in https://github.com/sparkletown/sparkle/commit/527e9a38bc66e45a58ae60d1c843abd2095453d7 that replaced profile pictures with a randomly chosen avatar, derived from `Math.floor(user.id.charCodeAt(0) % RANDOM_AVATARS.length)` when `USE_RANDOM_AVATAR` is set to `true` (as it appears to be for Burning Seed, in https://github.com/sparkletown/sparkle/blob/staging/src/settings.ts#L195)

It would be cool if users were able to choose/influence which of the default avatars they want to represent them on the paddock (I may biased'ly want to use [avatar-12](https://github.com/sparkletown/sparkle/blob/staging/public/avatars/avatar-12.png) :p)

While it would be an 'impactful' change (current random user avatars would end up being chosen differently), a naive minimal way that would allow user's to have some influence over this could be to use `user.partyName` in place of `user.id`, eg:

```diff
      const randomUrl =
        "/avatars/" +
        RANDOM_AVATARS[
-          Math.floor(user.id.charCodeAt(0) % RANDOM_AVATARS.length)
+          Math.floor(user.partyName.charCodeAt(0) % RANDOM_AVATARS.length)
        ];
```

**Comment by thecadams** [comment]
Hey, great idea! Would be very happy to accept a PR to change that!

**Comment by thecadams** [comment]
Noted - closing - hopefully you are able to put together a PR for this one!
