### ISSUE TITLE
Ability to mute sound effects (eg. howls, claps, etc) during Temple burn/similar

### ISSUE THREAD

**Issue by 0xdevalias** [sparkletown/sparkle#603]
Noticed at temple burn that there was a lot of noise spam, and a lot of people wishing they had an in-app way to mute them (without resorting to muting the whole tab, etc)

It would be cool if there was a mute button within the app or similar for these occasions.

**Comment by thecadams** [comment]
Noted. Happy to review a PR if you want to make the change!
