### ISSUE TITLE
partymap venue crashing if user has 10+ private chats 

### ISSUE THREAD

**Issue by margulies** [sparkletown/sparkle#829]
I think the problem may be related to a limit of 10 queries using the 'in' option in 'whereOptions':

https://github.com/sparkletown/sparkle/blob/e0c2565f23001a2f4c7efcbf3c7f87b7638bedee/src/components/molecules/Sidebar/Sidebar.tsx#L36

For a reference to this problem: [link](https://stackoverflow.com/questions/61354866/is-there-a-workaround-for-the-firebase-query-in-limit-to-10)

**Comment by thecadams** [comment]
Hey thanks for finding this. Just put through https://github.com/sparkletown/sparkle/commit/2cf4d883ec1624044c6f89f463764bbf6bc2b553 which should fix it!

**Comment by thecadams** [comment]
Closing this one. Please feel free to reopen if you feel it’s not fixed. Thanks for reporting it!

**Comment by 0xdevalias** [comment]
FYI, I've also just opened https://github.com/sparkletown/sparkle/pull/836 that fixes another bug with this.

**Comment by margulies** [comment]
This fix addresses the issue of the page not loading if the user has more than 9 private chats, however the new issue is that for all private chats older than the 9, the messages and profile image from the other user don't load. I imagine this is still linked to the query limit using "in"...

**Comment by 0xdevalias** [comment]
I believe @denisdimitrov may have been working on something related to this recently. He might be able to add some more context here and/or confirm if the above appears to still be an issue (or if not, in which PR we fixed it)

**Comment by thecadams** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bring Back Badges](https://trello.com/c/AAmGbZVs/447-bring-back-badges)

**Comment by margulies** [comment]
Just wanted to share that I found a temporary solution to this issue. Instead of restricting the user query based on prior private chats, I simply query for all users (though could it could also be restricted to attendees at specific party by querying 'enteredVenueIds'). The main change I implemented was replacing the following:

https://github.com/sparkletown/sparkle/blob/1a7d6f90a9a06ff046825a161df16bc9ac939902/src/components/molecules/ChatsList/ChatsList.tsx#L52-L73

with: 

`
  useFirestoreConnect([    
    {     
      collection: "users",    
      where: [["partyName", "!=", null]],    
      storeAs: "chatUsers",   
    },   
  ]);   
`

**Comment by 0xdevalias** [comment]
@margulies Thanks again for raising these issues and providing some solutions! Sorry it's taken me so long to get back to you, busy times!

I haven't checked if this is still an issue in the latest code, but I know that @mike-lvov is working on a big cleanup of our chat related code at the moment in https://github.com/sparkletown/sparkle/pull/1074

Since he's been looking at it all more recently than me, he might know whether this has already been fixed prior, or if his PR will fix it.

---

@mike-lvov When you have a chance, can you please check this out and let us know if this is either already fixed, or if your PR will fix it.

**Comment by 0xdevalias** [comment]
@malaikaaiyar @mike-lvov (or perhaps even @margulies) Can one of you please check if this is still an issue after the recent chat refactors.

**Comment by margulies** [comment]
Seems to be working now on my end, though definitely worth confirming elsewhere as well.

**Comment by malaikaaiyar** [comment]
It also works on my end. A different issue- I created like 7 new accounts to test this, and even after closing the window the 'people online' count is a lot higher than expected. Should I comment on older issues with this info?

**Comment by 0xdevalias** [comment]
> Seems to be working now on my end

> It also works on my end

@margulies @malaikaaiyar Awesome! I think we can call this issue closed then! 🎉 

---

> A different issue- I created like 7 new accounts to test this, and even after closing the window the 'people online' count is a lot higher than expected. Should I comment on older issues with this info?

@malaikaaiyar If we have any relevant currently open bug issues on the internal tracker, that's probably a good place to include that insight. If not, it's probably worth opening a new bug for it, and perhaps linking to any of the past issues/PRs that seem to be relevant for additional context.

**Comment by 0xdevalias** [comment]
Closing as the issue seems to have been resolved somewhere along the way of our recent refactors/fixes/etc.
